#!/usr/bin/env ruby
require './app'

def main
  Main.new.run
end

class Main
  def initialize
    puts 'Welcome to School Library OOP App!'
  end

  def menu
    puts
    puts 'Please choose an option by entering a number'
    @list = {
      1 => 'List all books',
      2 => 'List all people',
      3 => 'Create a person',
      4 => 'Create a book',
      5 => 'Create a rental',
      6 => 'List all rentals for a given person id',
      7 => 'Exit'
    }
    @list.each do |id, option|
      puts "#{id}: #{option}"
    end
    gets.chomp.to_i
  end

  def run
    results = App.new
    loop do
      choice = menu
      case choice
      when 1
        results.all_books
      when 2
        results.all_people
      when 3
        results.create_person
      when 4
        results.create_book
      when 5
        results.create_rental
      when 6
        results.list_rentals_of_person
      when 7
        puts 'Thank you for using this app!'
        exit
      else
        puts 'Please choose a number between 1 and 7'
      end
    end
  end
end

main
